name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Packaging"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    name: Publish distributions to PyPI
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/nirizan

    permissions:
      id-token: write

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v8
        with:
          name: python-distributions
          path: dist/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1